### ISSUE TITLE
Hex hashes case dependancy - **FALSE NEGATIVES**

### ISSUE THREAD

**Issue by magnumripper** [curlyboi/hashtopus#1]
When trying out hashtopus I fed it with some MSSQL hashes. None were cracked although I knew they should. After some serious head scratching I found out the following (I'm 99% sure):
- The hashlist I uploaded was in upper case hex `0xD3ADBAB3CAF3.....` (that's just how they happened to be formatted in my collection of samples).
- Hashcat **does** indeed crack them - but no sign of that anywhere in Hashtopus so we got a **false negative** (a.k.a _our worst nighmare_!)
- The reason is very likely that Hashcat writes the pot entries in lower case hex, so Hashtopus fails to match them with the upper case database entries!

The same problem can be seen in other parts of the program: When uploading pre-cracked hashes that doesn't match the case of the hashes in the database, they are also not recognized.

So, short-term workaround: Always import hex hashes in lower case. Long-term fix is not completely trivial: You ideally shouldn't do case-insensitive comparisons unless you KNOW the hashes are hex. If you do it to Base64 it could end up bad (although the risk of a false positive from doing so should normally be pretty slim).

**Comment by curlyboi** [comment]
Thanks for the info, i will take a look into that.

Might not be very soon because I am currently going thru some personal  
heavy stuff,
but I certainly don't want to abandon my baby project :)

Have a nice day,
cb.

Dne Wed, 03 Sep 2014 23:12:19 +0200 magnum notifications@github.com  
napsal(a):

**Comment by magnumripper** [comment]
Allegedly fixed in 941d931ac
