### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#11]
Launching the agent. After entering your voucher it says logging in and then crashes
http://gyazo.com/1789b607c98654b36445850284930e68.png

edit:
web version seems to be 0.9.2 while downloadable agent seems to be 0.9.3

**Comment by winxp5421** [comment]
Run "Hashtopus.exe debug" in command line should give a little more info on what is happening.

**Comment by ghost** [comment]
http://gyazo.com/324978d18c3a09f6b0b5c19b41bb9d08.png

**Comment by curlyboi** [comment]
I just uploaded a new version with richer debug output. Please download it (agent should show 0.9.4) and start it with debug again. Thanks.

**Comment by ghost** [comment]
http://gyazo.com/cd1499a82af43dd3f48ddd874985bea2.png
http://gyazo.com/a9ed477208ad2700e91cf5e851dcdc9b.png

**Comment by curlyboi** [comment]
A-ha!

You are using Catalyst 14.12 but on hashcat.net it's specified that you need 14.09 exactly. Nevertheless, I fixed this in 0.9.5, please try it.
