### ISSUE TITLE
Multiple files per task

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#12]
From what I can see, you can't have more than one file per task.
http://gyazo.com/6295c07eba6c51e4f3a83a0aa51d0599.png
http://gyazo.com/c783c7a3d0aded90e7a2d33f0e02398c.png

**Comment by curlyboi** [comment]
It must be your specific case - my database looks different. Please always
try to replicate bugs in fresh installation package before submitting bugs.

2015-04-27 20:53 GMT+02:00 NullPatrol notifications@github.com:

**Comment by ghost** [comment]
DROP TABLE IF EXISTS `tasks`;
/_!40101 SET @saved_cs_client     = @@character_set_client */;
/_!40101 SET character_set_client = utf8 _/;
CREATE TABLE `tasks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE latin1_bin NOT NULL COMMENT 'Task name',
  `attackcmd` varchar(256) COLLATE latin1_bin NOT NULL COMMENT 'Hashcat command line',
  `hashlist` int(11) DEFAULT NULL COMMENT 'Hashlist ID',
  `chunktime` int(11) NOT NULL COMMENT 'Chunk size in seconds',
  `statustimer` int(11) NOT NULL COMMENT 'Interval for sending status',
  `autoadjust` tinyint(4) NOT NULL COMMENT 'Indicator if agents benchmarks are automaticaly adjusted',
  `keyspace` bigint(20) NOT NULL DEFAULT '0' COMMENT 'Keyspace size (calculated by Hashcat)',
  `progress` bigint(20) NOT NULL DEFAULT '0' COMMENT 'How far have chunks been dispatched',
  `priority` int(11) NOT NULL DEFAULT '0' COMMENT 'Assignment priority',
  `color` varchar(6) COLLATE latin1_bin DEFAULT NULL COMMENT 'Color of task shown in admin',
  PRIMARY KEY (`id`),
  KEY `adm_usage` (`hashlist`),
  KEY `autoassign` (`progress`,`keyspace`,`priority`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 COLLATE=latin1_bin COMMENT='List of tasks';
/_!40101 SET character_set_client = @saved_cs_client */;

this is how it's written in the hashtopus.sql you download from http://hashtopus.nech.me/beta/
if it's int, then how can you have multiple?

**Comment by curlyboi** [comment]
this is not about table "tasks" but about "taskfiles". there can be multiple lines regarding the same task with multiple files.
