### ISSUE TITLE
Speed not updating

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#13]
I've created a custom statistics page including a graph to represent the speed of cracking.
But I notice that if an agent stops cracking it will not return it's speed to 0. Instead it keeps it at its latest value.
Is there any way you could make it reset to 0 if it hasn't changed in 10 seconds for example?

**Comment by curlyboi** [comment]
I can implement this, but only partially.

You see, if I had to check it every 10 seconds, there would have to be some kind of scheduled job (cron perhaps?).

So what I can do is that if agents stops cracking and it asks for new task and you get that message "Loading task...failed: No active tasks." it will reset the agent speed to 0.

But, if the agent crashes for example, there is no way to catch this on the server side.

**Comment by curlyboi** [comment]
See the last commit. Just line 249 in server.php.

**Comment by ghost** [comment]
What if a user would close it manually, not a case of crashing but the 'X' button.
Would there be a chance of an: onExit function to execute?

**Comment by curlyboi** [comment]
Yes, I will implement this too.

**Comment by curlyboi** [comment]
Done, get 0.9.7
