### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#17]
Could you add an option to only show the text:

Hashcat Running: [xx,x%/100%]
or
No Active Task

Clear screen each time a new % is posted?
Maybe call this the 'simple display'

**Comment by curlyboi** [comment]
how about the other texts? like loading tasks, downloading files, etc

**Comment by ghost** [comment]
Make it a checklist and make it build a binary or save it by agent.

Agent: John-PC
Task: 12
Run Time: 1d | 5h | 1m | 32s
Chunk Time Left:  0d | 1h | 35m | 1s
Process: [32,1% / 100%]
Note: Patience is a virtue

Agent: John-PC
Task: 0
Run Time: 0s
Time Left:  0d | 0h | 0m | 0s
Process: Awaiting New Task
Note: wordlist1.txt [25MB] [23%]

Agent: John-PC
Task: 13
Run Time: 0s
Time Left:  0d | 0h | 0m | 0s
Process: Downloading New Files [1/1]
Note: wordlist1.txt [25MB] [23%]

**Comment by curlyboi** [comment]
So you want some API for hashtopus server then? I suggest you code it yourself, this is way to specific and PHP is easy enough.

**Comment by ghost** [comment]
You interpret me wrong.
Not this:
https://gyazo.com/689bf4b1d0879829934f2b3f639c8d9d.png

But this:
https://gyazo.com/3c7c151deb4521445f15382d1346d1a1.png
https://gyazo.com/8e6a6c8cbd9a82e92f0c1feac9c9a08b.png

So it's still cracking hashes, but it displays differently

**Comment by curlyboi** [comment]
why not get this all info from server instead?

or is it for the user?
Dne 7. 9. 2015 17:37 napsal uživatel "NullPatrol" <notifications@github.com

**Comment by ghost** [comment]
This is for the client that the user runs on their PC that displays stats from hashcat.

**Comment by ghost** [comment]
This means there is no point to get 'that info' from the server since it will still run the command prompt on the agent's pc
