### ISSUE TITLE
Storage of hashes

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#18]
Optional to store the cracked hashes so they can be checked and see if any have been cracked before.

Checklist with all methods so they can be checked.

Storage done as follows: 

Table Name: MD5
id | type | hash | salt | plaintext 
1 |   0     |abcd |        | test
2 |   10   |acef  | ace | teste

Table Name: SHA1
id | type  | hash | salt | plaintext
1 |  100  | abca |        | nose
2 |  120  | acde | ace | toes

MD5 will store all types of MD5 hashes (MD5x2 and salted too
SHA1 will store all types of SHA1 and so on.

if the MD5 value is "acef" return testeace
if the SHA1 value is "acde" return acetoes
if the MD5 value is "acef:ace return teste

(optional to import existing lists of cracked hashes)

**Comment by ghost** [comment]
I'm willing to help develop & code this with you if you're interested in this.

**Comment by curlyboi** [comment]
I'm struggling what would be the benefit of such feature?

**Comment by ghost** [comment]
I would like to scrap the Salt part of this idea, however, Storing the MD5's and SHA1's (checkboxes for methods) will allow lookups to remove the previously cracked hashes from a database

**Comment by curlyboi** [comment]
this is essentialy what superhashlists are for
Dne 7. 9. 2015 17:21 napsal uživatel "NullPatrol" <notifications@github.com
