### ISSUE TITLE
Wrong separator on hashlist

### ISSUE THREAD

**Issue by baznikin** [curlyboi/hashtopus#19]
Hello! Trying to run type 2611 salted hash attack againist already known plaines to check how thing work and got nothing. Hashlist separator is ":", but hastopus pass 0x01 as separator to agent:

> C:\programs\hashtopus\hashcat\oclHashcat32.exe -a 0 "C:\programs\hashtopus\hashlists\8" "C:\programs\hashtopus\files\leg_planes_2013" --hash-type=2611 --potfile-disable --quiet --restore-disable --session=hashtopus --status --status-automat --status-timer=5 --outfile-check-dir="C:\programs\hashtopus\hashlists\zaps8" --outfile-check-timer=5 --remove --remove-timer=5 --separator=**0x01_is_here** --skip=0 --limit=839

**Comment by curlyboi** [comment]
thats fine, the 01 is used later during cracking but in admin the separator
is defined as : (default, can be changed). just check it saves well into
the db by using myadmin
Dne 15. 8. 2015 19:50 napsal uživatel "baznikin" notifications@github.com:

**Comment by baznikin** [comment]
So fast reply! :+1: Noticed this just now and wanted to close issue. Still got nothing, trying to figure out how to use hashtopus correctly

**Comment by curlyboi** [comment]
i am only on mobile so i cant check. what hashtype is 2611?
Dne 15. 8. 2015 19:55 napsal uživatel "baznikin" notifications@github.com:

**Comment by baznikin** [comment]
It is vBulletin < v3.8.5 hash. Successfully runned hashcat againist this hashlist few years ago

**Comment by curlyboi** [comment]
try importing it as unsalted hash, some of these special hashes behave as
if the salt was part ofthe hash itself. always ask yourself: "can the has
exist also unsalted?" if not, chance is you should treat it like ordinary
unsalted hash
Dne 15. 8. 2015 19:58 napsal uživatel "baznikin" notifications@github.com:

**Comment by baznikin** [comment]
It was my bad - badly prepared planes list, didn't strip it from hashes.
PS: I suppose I'll send pull requests soon :D
