### ISSUE TITLE
Issue with compressed wordlist

### ISSUE THREAD

**Issue by baznikin** [curlyboi/hashtopus#20]
Hashtopus runs hashcat with relative path to extracted wordlist instead of absolute (as it does when wordlist is uncompressed):

> C:\programs\hashtopus\hashcat\oclHashcat32.exe -a 0 "C:\programs\hashtopus\hashlists\13" **uniqpass_v15.???** --hash-type=2611 --session=hashtopus --keyspace --quiet

Also mask "file.???" will match compressed and uncompressed files at same time. 

```
C:\programs\hashtopus>dir files\uniqpass_v15.???

16.08.2015  02:04                 8 uniqpass_v15.7z
10.01.2015  14:56     2 662 269 445 uniqpass_v15.txt
```

If I try to run hashcat manually with right path to wordlist directory and file mask file.??? as argument hashcat failed to run:

> ERROR: --keyspace is not supported with --increment or mask files

My suggestion is to check file name inside of archive during extracting, keep it inside of file.7z (i.e. "UNPACKED file.txt") and use it later to build actual path.
Another approach is to force file naming scheme with full name of file inside of archive like 'file.txt.7z' for 'file.txt' then you'll always know what file name to use.
Best path is to read archive content at upload time on server and keep inner file name in DB and pass it to agent to run.

Full debug output:

```
Hashtopus 0.9.7
Debug mode on.
Logging in to server...OK.
Windows OS detected.
AMD detected.
Parsing driver version from '14.9'
Loading task...assigned to 18, hashlist 13 (continue)
Downloading file uniqpass_v15.7z...
10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
Extracting archive C:\programs\hashtopus\files\uniqpass_v15.7z...
C:\programs\hashtopus\7zr.exe x -y -o"C:\programs\hashtopus\files" "C:\programs\hashtopus\files\uniqpass_v15.7z"
Hashlist already exists.
Requesting chunk...keyspace measuring required
Measuring keyspace...C:\programs\hashtopus\hashcat\oclHashcat32.exe -a 0 "C:\programs\hashtopus\hashlists\13" uniqpass_v15.??? --hash-type=2611 --session=hashtopus --keyspace --quiet
WARN: ADL_Overdrive6_FanSpeed_Get(): -1
ERROR: uniqpass_v15.???: No such file or directory

ERROR -1
[ERR] Uploading 99 b...Uploaded 2 errors
Windows OS detected.
AMD detected.
Parsing driver version from '14.9'
Loading task...failed: No active tasks.
Waiting for next assignment...
```

**Comment by baznikin** [comment]
Issue text updated with additional info and suggestions.

**Comment by curlyboi** [comment]
read manual. you need to use inner filename in thr attack command line.
thats why it enters the .??? when you checj the file
Dne 15. 8. 2015 22:10 napsal uživatel "baznikin" notifications@github.com:

**Comment by baznikin** [comment]
My bad! What do you think about improving of compressed file management?

> Best path is to read archive content at upload time on server and keep inner file name in DB and pass it to agent to run.

If you don't mind to include this feature I can try to code it.

**Comment by curlyboi** [comment]
that would require 7z library for php and also archive can contain multiple
files... sounds like a nice feature but a little unnecesary
Dne 16. 8. 2015 19:04 napsal uživatel "baznikin" notifications@github.com:
