### ISSUE TITLE
Salts with symbols \ and separator char

### ISSUE THREAD

**Issue by baznikin** [curlyboi/hashtopus#21]
I have hashlist type 2611 (vBulletin forum) and current insertion method can't handle it. Salt in this format consists of pretty all latin1 printable characters.
- "\" symbol in most cases is simply stripped out
  
  > -aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:U\m
  > +aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:Um
- "\" in the end of salt corrupts two lines
  
  > -aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:?w\
  > -bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb:[A}
  > +aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:?w
  > +bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
- separator symbol (":" in my case) as expected split salt in separate fields. There 
  
  > -aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:":i
  > +aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa:"
  > There is workaround for this case in using unprintable character but you can't simply enter it in form input (at least I can't enter \0x01 in Chrome using ALT+01 or Ctrl+V)

All those cases can be handled by regular expression (smth like `/^([^$SEP]+)$SEP(.+)/`) on line-by-line inserts but I can't see how to handle it with LOAD DATA

**Comment by baznikin** [comment]
Successfully load hashlist by escaping : & \ in salts. Maybe it is simpler to note it in manual than workaround it in code

**Comment by curlyboi** [comment]
How did you escape it?

**Comment by baznikin** [comment]
I escaped '\' and separator:
\ → \
: → :

воскресенье, 6 сентября 2015 г. пользователь cURLy bOi написал:

**Comment by curlyboi** [comment]
Thanks for the heads-up
