### ISSUE TITLE
HC release ordering

### ISSUE THREAD

**Issue by baznikin** [curlyboi/hashtopus#23]
Upon hashcat update request most modern version choosed by platform and installed driver version. When multiple hc version matches request hashtopus choose one by ''date'' field.
1. Obviously one doesn't have to enter hc releases in release order (i.e. I can add 1.37 then 1.35).
2. New hc release added with web interface is in unix timestamp format, but supplied with hashtopus SQL script isn't:

```
MariaDB [hashtopus]> SELECT version,time,minver_amd FROM hashcatreleases WHERE minver_amd<=1409 ORDER BY time DESC LIMIT 5;
+---------+----------------+------------+
| version | time           | minver_amd |
+---------+----------------+------------+
| 1.36    | 20150814004056 |       1409 |
| 1.37    |     1440124297 |       1409 |
+---------+----------------+------------+
2 rows in set (0.00 sec)
```

Workaround is to keep only one most recent release.

**Comment by curlyboi** [comment]
i will look into this, thanks.

**Comment by curlyboi** [comment]
Fixed the installation script.
