### ISSUE TITLE
Hash is cracked but not returned to server

### ISSUE THREAD

**Issue by erlingn** [curlyboi/hashtopus#25]
Hi!
I experienced issues with hashes stopping with status 'cracked' but nothing appeared in the web gui.

Upon searching the web, I found that "cryptolovi" from the hashcat.net forum had also experienced this and posted a fix. https://hashcat.net/forum/thread-3159-post-25234.html#pid25234

> To see if you are affected look for "PHP Notice: Undefined variable: HTTP_RAW_POST_DATA in server.php on line 641" in your http daemon logs.

``` php

if (strlen($HTTP_RAW_POST_DATA)>0) {
$data=explode($newline,$HTTP_RAW_POST_DATA);
```

to

``` php
if (strlen(file_get_contents("php://input"))>0)
$data=explode($newline,file_get_contents("php://input"));

```

Perhaps this or something like it should be implemented. I don't know if the new function is backwards compatible or not. I leave it up to you master coder! :)

**Comment by timonline** [comment]
@erlingn I could hug you!!!!!!!!!!! This problem has been driving me crazy :angry: :facepunch: 

I checked the http daemon logs, found the exact error you mentioned ("PHP Notice: Undefined variable: HTTP_RAW_POST_DATA in server.php on line 641"), made the changes in server.php, and BAM it worked.

Thank you Thank you Thank you :+1:

**Comment by curlyboi** [comment]
interesting. what php are you using?
Dne 6. 9. 2015 23:07 napsal uživatel "timonline" notifications@github.com:

**Comment by timonline** [comment]
PHP Version 5.6.12-0+deb8u1, here's the screenshot of phpinfo

![screenshot from 2015-09-06 23 27 15](https://cloud.githubusercontent.com/assets/500310/9706727/e813d2b6-54bc-11e5-9358-01692551feec.png)

**Comment by curlyboi** [comment]
Added to main branch.
