### ISSUE TITLE
Add CPU hashcat interface

### ISSUE THREAD

**Issue by Maxiz80** [curlyboi/hashtopus#27]
Hello.
Could be possible to insert support for hashcat 0.50 for cpu?

**Comment by curlyboi** [comment]
It might be possible but you cannot combine CPU and GPU agents in one task.

**Comment by Maxiz80** [comment]
Obviously..

**Comment by Maxiz80** [comment]
Some update planned?

**Comment by curlyboi** [comment]
I don't have too much time to do new features right now.

**Comment by Pentoman** [comment]
Could be closed the new Hashcat Release is there it supports GPU+CPU

**Comment by Maxiz80** [comment]
I agree but you must implement in you server file..

**Comment by curlyboi** [comment]
i am working on this now

**Comment by curlyboi** [comment]
hashcat 3.0 works with hashtopus 1.2
