### ISSUE TITLE
BIG BUG

### ISSUE THREAD

**Issue by Maxiz80** [curlyboi/hashtopus#28]
Hello.
you know that you can't add more than 6 agents? :)

**Comment by curlyboi** [comment]
Obviously I don't know. Would you be so very kind and share some technical details with us instead of teasing us with such mystical question? :P

**Comment by Maxiz80** [comment]
I create 7 voucher.
I start to insert in them in the agents.
Until 6 it's all ok and they're added regoularly.
But when I add the 7th the 6th agent in the list get replaced by 7th..

**Comment by curlyboi** [comment]
This might be caused by duplicity in the ID of the computer. I have system with like 20 agents and it works perfectly fine. Perhaps you cloned a vmware or something?

**Comment by curlyboi** [comment]
Regardless, I have fixed this behaviour in 0.9.8, it didnt make sense
