### ISSUE TITLE
Create hashtopus client-side service

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#29]
https://github.com/curlyboi/hashtopus/issues/17
I believe you misunderstood me and closed it preemptively 
would you mind taking another look?

**Comment by curlyboi** [comment]
I undestand the question but the request is far too specific. If I were to do this, it would have to be more complex like moving all the strings into external file where the user could change all the application output. Since you are the only one who have requested the feature, I don't give this a high priority.

**Comment by ghost** [comment]
I believe it's just limiting the data displayed. I think most data is already sent back and forth to the server.

**Comment by curlyboi** [comment]
That is true but the agent is meant to be unattended and my original intention was to make the agent a windows service. But in the windows service session, GPUs don't work properly so I had to resort to console application. So once it was clear I cannot make it run in the background, the console was just the easiest option for UI, I wasn't going to put much effort to it.

**Comment by baznikin** [comment]
BTW, service will be nice addition to hashtopus, it's only task should be
to run console application in current session (not sure is service able to
do so). I suppose it can be same executable

воскресенье, 8 ноября 2015 г. пользователь cURLy bOi написал:

**Comment by curlyboi** [comment]
I will look into the service.

**Comment by curlyboi** [comment]
Implemented in 1.3
