### ISSUE TITLE
Php Errors

### ISSUE THREAD

**Issue by meneken17** [curlyboi/hashtopus#31]
hey there
I always get some php errors running hastopus on my xampp server.

On the Login Mask
Notice: Undefined index: auth in C:\Program Files (x86)\xampp\htdocs\hashtopus\admin.php on line 99

On admin.php page, after clicking on the Hashtopus button in the menu
Notice: Undefined index: a in C:\Program Files (x86)\xampp\htdocs\hashtopus\admin.php on line 153

On admin.php?a=taskdetail&task=1
Notice: Undefined index: all in C:\Program Files (x86)\xampp\htdocs\hashtopus\admin.php on line 2426

And (pretty annoying) in the Hashtopus.exe download file:
Notice:  Undefined index: hash in C:\Program Files (x86)\xampp\htdocs\hashtopus\server.php on line 99

Is there something wrong with your programm or am I doing somthing wrong?

**Comment by curlyboi** [comment]
You need to disable notices in error output. What you have enabled is
developer configuration which whows even the tiniest and most unimportant
problems.

2015-11-23 22:25 GMT+01:00 meneken17 notifications@github.com:

**Comment by ghost** [comment]
Why not fix those small unimportant problems like adding an isset or adding quotes?

**Comment by curlyboi** [comment]
Hmm, you are right. Fixed that shit.
