### ISSUE TITLE
hashtopus.exe will not download newest Hashcat when adding clients

### ISSUE THREAD

**Issue by coffeebro** [curlyboi/hashtopus#32]
This is due to the release of hashcat 2.01

This can be fixed by adding the following piece of code to the "hashtopus.sql" file:

INSERT INTO `hashcatreleases` (`version`, `time`, `url_nvidia`, `url_amd`, `common_files`, `32_nvidia`, `64_nvidia`, `32_amd`, `64_amd`, `rootdir_nvidia`, `rootdir_amd`, `minver_nvidia`, `minver_amd`) VALUES
('2.01', UNIX_TIMESTAMP(NOW()), 'http://hashcat.net/files/cudaHashcat-2.01.7z', 'http://hashcat.net/files/oclHashcat-2.01.7z', 'hashcat.hcstat hashcat.keyfile', 'kernels/4318/_32.ptx', 'kernels/4318/_64.ptx', 'kernels/4098/_.llvmir', 'kernels/4098/_.llvmir', 'cudaHashcat-2.01', 'oclHashcat-2.01', 34600, 1409);

I have forked and committed these changes if you would like to merge them.  Thanks!

**Comment by curlyboi** [comment]
This has been fixed in the newest release.
