### ISSUE TITLE
File Size / importing limitation

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#34]
For some reason it doesn't want to import files larger than a certain size.
I notice it always stopping at 1100001 hashes.

**Comment by curlyboi** [comment]
So you are importing a hashlist, not a global file, right?
What import method are you using?

**Comment by ghost** [comment]
default import from import folder. I fixed it with adding a mem limit(-1) and a prevention of user interference to the admin.php file.

**Comment by curlyboi** [comment]
Ok, this breaks down to PHP/web server configuration so closing.
