### ISSUE TITLE
Split string issue importing hass

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#37]
e86ac4927a1307e52a026b36a0963444:sof7Lvg|fR'mdQ:OI3Hb5H'E8sZ-y!:123456
f42266f16c0742edaef1905b6a67fd3e:;>DHb&_C(je_i;{Pv#>])r\WY9AO:&:qwerty
e02c76e38605d22b16eb84bd6bbaf0bb:Py4~PCL~aZ=20:e[QWlfUFT0jVgRU_:gamecube
f0ba1b62eb12ce58f6234d910a3533c0:?F#'8ybRm:y}AUkS8<Ts?]yh8n#m8.:abc123
709e8878a6e5335a1dd65cd08e76812f:YcB~>M]yUzO*___6Nr.'gHm8_6gT:.:111111
9df550a0f085c33ef614dc0506420aff:F#-S6b!:c9nBwmu]r7l4N9oe[:)p73:football
0c0844db6956a3d5bbff4ffb69b6d3da:y:>Jb@!hl|N_xW63Kqn27s/_9el=J?:monkey1
fbdd0eb87d822df8773a8a841f0f66fd:aQWrZ|G9[T!XIDv3<ebDD\nu<j7Z:@:chicken
72c938dae7a8a15ade6127815337b7ef:Ra'sz'8(Q:%9}Xy/l9i9gjTP4vGQ&M:thunder
b2227d600cbd631e7d65202aada129b0:#/Nd/0g\PR.(0*#pi3Vb_T5kf?:%Rq:123456
7577beac135bb69ec684167bcbf95152:MfZ[^58Rul]}=Qg0W3()%~:3LRt_&}:liverpool
277447c26101438e1324437c8abe0f28:?en>Hz!13Fh0:(opa6-uU5.t1M?j~:password
654ef82b3e8803b93fc36c5b62504f06:k\Za61{cocxuizXGB`SJtN1:6/VuI%:123321

It seems as though salts with : can't be imported correctly.
What if you have a salt with a : and a plain with a :?

Could you look into a fix for this?

**Comment by winxp5421** [comment]
This is an issue but a valid work around is import them into hashtopus using a different delimiter such as the pipe "|"

**Comment by ghost** [comment]
fbdd0eb87d822df8773a8a841f0f66fd:aQWrZ|G9[T!XIDv3 

for example contains a |
what if a salt and plaintext contain the same "delimiter/string"
what if the plaintext was within the salt by sheer coincidence.

**Comment by curlyboi** [comment]
this is common problem with string delimitation and one that i have struggled with during interfacing between hashcat and hashtopus as well. the "delimiter" setting in hash import screen is there for that exact reason.
