### ISSUE TITLE
HTTP error: An exception occurred during a WebClient request.

### ISSUE THREAD

**Issue by freeload101** [curlyboi/hashtopus#39]
First off great work! I love to get it working properly and contribute so I can quickly add agents.  I got a free 300$ GPU sitting on my network and access to 2 more so I thought I would give this a go...Ugh its hArD ...It looks like in my case I will just use -s and -l  ( https://hashcat.net/forum/thread-3047.html )  You should add batchcrack to the task list ! https://rmccurdy.com/scripts/batchcrack_rmccurdy_UBUNTU.sh 
# 

Hashtopus 0.9.8
Registering to server...Enter registration voucher: ccc
HTTP error: An exception occurred during a WebClient request.

the url appers to be ok .. nothing in the logs and nothing in TCPdump the host is setup localy tho ..
$ tail -c 50 hashtopus.exe
         http://ocl.tunnel.rmccurdy.com/server.php
# 

some other notes I have sofar before I gave up for the night:
- why is there  a custom zip for  Cuda ?? cudaHashcat**hashtopus**-2.01.7z its a 404 anyway ..  "http://hashcat.net/files/cudaHashcat-2.01.7z"
- readme should include port info and config for firewalls etc
- 'import' folder goes in the base path of the other files " this folder should be automaticly added to the .sql script not sure why it is not .. 
- the SQL php worked but noytihng in the hashcatreleases table .. I think windows does not like that "UNIX_TIMESTAMP(NOW())" if I force it phpmyadmin says unregnized keyword but filles in the info

**Comment by curlyboi** [comment]
It works for my setup which is also windows apache + php + mysql.

The HTTP error will probably be some PHP message which gets in a way when registering the client.

If you could capture the HTTP request, you would see whats going on.

**Comment by curlyboi** [comment]
closing for no response.
