### ISSUE TITLE
Missing hashtopus.exe

### ISSUE THREAD

**Issue by Ne0nd0g** [curlyboi/hashtopus#4]
First I wanted to say thank you for developing this tool, I really enjoy everything you have done. I did a "git clone" to get started using your application. I was having the hardest time getting the agent to run after downloading it. I finally realized that the hashtopus.exe is not included with this repo. I ended up pulling down the files from http://hashtopus.nech.me/beta/hashtopus128.7z and extracting hashtopus.exe to the web root. Now everything appears to be working fine.

**Comment by Ne0nd0g** [comment]
I'm not sure if you are allowed to distribute hashcat with this repo, but you might also want to create the "files" directory in this repo and potentially include hashcat in it.

**Comment by Ne0nd0g** [comment]
And a blank "import" directory

**Comment by curlyboi** [comment]
Yes, git only hosts the source, while the beta 7z contains the binary as well. I just didn't want to distribute the binary using github.
