### ISSUE TITLE
clCreateProgramWithBinary -42

### ISSUE THREAD

**Issue by ghost** [curlyboi/hashtopus#41]
https://i.gyazo.com/ad7761bb2a0739fd24489c827b386b30.png

Unsure why this appeared but obviously something is wrong and I can't find the cause.

**Comment by curlyboi** [comment]
This is hashcat error. Hashtopus just directly prints it out.

**Comment by Dyson78** [comment]
i get something close to this I get "Hashcat (keyspace) exited with return code -1"

**Comment by curlyboi** [comment]
yes, hashtopus recognized that hashcat failed to run and reported it
