### ISSUE TITLE
Error in SQL file from Beta Download

### ISSUE THREAD

**Issue by ryanvillarreal** [curlyboi/hashtopus#42]
The beta version you have downloadable on your site has an error with the hashtopus.sql file.  It seems to be missing the values of the hashtypes.  I am not sure if this has been addressed elsewhere, but to fix I just copied the previous sql file hashtypes section into the new sql file.  Or you could just update the hashtopus.sql file currently on Github to point to the new cudaHashcat-2.01.7z files. 

Sorry if this is the wrong place to address this.  

Thanks!

**Comment by kolet** [comment]
thanks, that was helpfull.

**Comment by curlyboi** [comment]
only hashcat 3.x is supported now
