### ISSUE TITLE
Cant incremental nor hmask

### ISSUE THREAD

**Issue by kolet** [curlyboi/hashtopus#43]
first thing first,
thanks alot for ur work and time that u put into this for all the community. much love <3

when u do incremental or hcmask that what u getting
Measuring keyspace...ERROR: --keyspace is not supported with --increment or mask files

when using

-a 3 #HL# ?a?a?a?a?a?a -1 ?a –increment –increment-min=1 –increment-max=6

or

-a 3 #HL# ?a?a?a?a?a?a –increment –increment-min=1 –increment-max=6

client crash on windows. and on linux machine “ERROR: –keyspace is not supported with –increment or mask files”

same as mask file,

-a 3 -1 ?a #HL# 8len2d6low1U.hcmask

-a 3  #HL# 8len2d6low1U.hcmask

however u can #HL# 8len2d6low1U.hcmask but that does nothing 😉

same thing when u pre-task and add the pre-task to an hash list.

putting each mask on a pre-task will be horrible my mask file as 1839 lines = 1839 masks
i cant imaging myself copy pasting each line , or giving this pretask to an hashlist.

thanks :)

**Comment by curlyboi** [comment]
incemental does not work in hashcat when using -s and -l this is not problem of hashtopus per se.

**Comment by curlyboi** [comment]
this was added in 1.5
