### ISSUE TITLE
New Hashcat!!!

### ISSUE THREAD

**Issue by Pentoman** [curlyboi/hashtopus#44]
There is a new Hashcat !! on Git or as Zip Download , its brand new now with fusion of AMD and NVIDIA and it uses CPU also , please implement it .... many changes ....

**Comment by ghost** [comment]
As far as i'm concerned you can still manually install hashcat and get the same results

**Comment by hydrocloricacid** [comment]
I tried that, didn't work.  The commandline option --status-automat which is in (ocl|cuda)hashcat 2.01 is replaced by --machine-readable in hashcat 3.00 .

Hashcat 3.00 sadly enough doesn't recognise the --status-automat option. Pity it didn't keep it in for compatibility.

**Comment by winxp5421** [comment]
i will just leave this here https://bitbucket.org/seinlc/hashtopussy

**Comment by hydrocloricacid** [comment]
Legend !

Thanks winxp for this & Curlyboi for Hashtopus

**Comment by curlyboi** [comment]
new hashtopus
