### ISSUE TITLE
Hashcat release

### ISSUE THREAD

**Issue by Maxiz80** [curlyboi/hashtopus#45]
Hi.
I can't create hashcat releases..
Why?

**Comment by metulski2013** [comment]
The file should have the Extension zip, you must repack the 7zip file from hashcat. it should have the name "hashcat.zip" to prevent further problems during installation of the client.

**Comment by curlyboi** [comment]
use the hashtopus-hcdownloader to deliver hashcat releases to your system. it will repack 7z to zip and only include necesary files.
