### ISSUE TITLE
$dblink

### ISSUE THREAD

**Issue by Maxiz80** [curlyboi/hashtopus#46]
What I'm doing wrong?
I continua to receive error
Notice: Undefined variable: htphost in C:\xampp\htdocs\admin.php on line 2

Notice: Undefined variable: dblink in C:\xampp\htdocs\common.php on line 12

**Comment by AUmrysh** [comment]
I'm having the same issue. Ubuntu with nginx using php5-fpm

**Comment by curlyboi** [comment]
fixed in last commit 1.5e
