### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tillkoeln** [curlyboi/hashtopus#49]
Goood Morning, 

please could someone tell me, how much Clients can work with the Server at the same time ? 
exist there any Limitation ? 

Thank You in advance
Tillkoeln

**Comment by winxp5421** [comment]
Only limit is the resources your server has.

**Comment by Tillkoeln** [comment]
Thank You for your fast reply,

**Comment by winxp5421** [comment]
Np, kindly close ticket please
