### ISSUE TITLE
.hcmask Support for Tasks

### ISSUE THREAD

**Issue by Atticuss** [curlyboi/hashtopus#5]
Heyo. Great tool, loving it so far. Only gripe is the inability to pass hcmask files into tasks. I understand this is an oclhashcat restriction due to keyspace calculations; however, being able to generate a single task for each entry in a supplied .hcmask would prove very beneficial. Thoughts?

**Comment by curlyboi** [comment]
Perhaps an automated task generator based on text file/textarea where every line from the text file would be used on specified place in the task command?

**Comment by Atticuss** [comment]
Perhaps. If you end up with a new task for every line in the hcmask file, you would blow up your management console pretty quick. Haven't had a chance to look through your source yet so I can't really comment any further than that.

**Comment by huntergregal** [comment]
I too would be interested in this support. I am heading a research project for my university and we are using hashtopus. .hcmask support would be awesome.

**Comment by ghost** [comment]
How about an import method to convert a .hcmask file (format) to a supertasklist (combination of multiple tasks).

Super task lists could be used to directly select a certain order of doing multiple tasks like an quick md5 scan or an intensive MyBB scan

**Comment by curlyboi** [comment]
Implemented in 1.5

**Comment by Atticuss** [comment]
Ayy, awesome man. Look forward to giving it a spin.
