### ISSUE TITLE
Cannot import files from 'Import' folder

### ISSUE THREAD

**Issue by rssoc** [curlyboi/hashtopus#56]
When I try to import my files from said folder, it gives me this.
`Adding file files/best64.rule:
Loading imported file...DST ERROR`
`Adding file files/rockyou.txt:
Loading imported file...DST ERROR`
`Adding file files/rockyou-30000.rule:
Loading imported file...DST ERROR`
`Adding file files/hashkiller-dict.txt:
Loading imported file...DST ERROR`
`Adding file files/rule1.rule:
Loading imported file...DST ERROR`
`Adding file files/rule2.rule:
Loading imported file...DST ERROR`

**Comment by JuggyMcNutty** [comment]
make sure the user www-data is the owner of all directory's and files. and set permissions to 775

**Comment by rssoc** [comment]
Huh, that was the first thing I did. But after doing it again, everything is working perfectly! Thanks :smile:

**Comment by curlyboi** [comment]
DST means destination, SRC means source, so DST error is problem writing to where the data are being copied.
