### ISSUE TITLE
cant add new releases

### ISSUE THREAD

**Issue by Lumb3rH4ck** [curlyboi/hashtopus#57]
cant add new releases to hastopus so none of my clients can download hashcat. all working server side and clients can connect fine but just cant get a new release of hashcat onto the server. 

http://imgur.com/a/4xEo6

**Comment by Lumb3rH4ck** [comment]
Turns out im being lazy and should have read the manual properly... please delete or send hate mail or whatever

thanks for hashtopus, your a legend mate

**Comment by curlyboi** [comment]
pebkac :)
