### ISSUE TITLE
Issue running agent on Kali Linux x64

### ISSUE THREAD

**Issue by rssoc** [curlyboi/hashtopus#58]
Output when running mono
`root@kali:/var/www/html# mono hashtopus.exe` 
`WARNING: The runtime version supported by this application is unavailable.`
`Using default runtime: v4.0.30319`
`Use mono-service to start service processes`

Output when trying to get libmono-2.0cil
`root@kali:~/Desktop/newtmp# apt-get install libmono-2.0cil`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`E: Unable to locate package libmono-2.0cil`
`E: Couldn't find any package by glob 'libmono-2.0cil' `
`E: Couldn't find any package by regex 'libmono-2.0cil' `

**Comment by curlyboi** [comment]
seems the packaging have changes, i should update the manual

**Comment by rssoc** [comment]
So what do I do? What runtime do I install instead?

**Comment by rssoc** [comment]
Fixed the issue by running `apt-get update'. Now I'm greeted with 
```
root@kali:~/Downloads# mono hashtopus.exe debug
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
Hashtopus 0.9.9.1
Debug mode on.
CPU is 64 BITS
lspci 
uname -n
blkid /dev/sda5
Registering to server...Enter registration voucher: cluster 
HTTP error: The remote server returned an error: (500) Internal Server Error.
```
i'm assuming this is some sort of mySql error?

**Comment by curlyboi** [comment]
this is server error - you have something wrong with the web server where you have the PHP scripts

**Comment by rssoc** [comment]
Yes, I just checked and it was a permission issue.
