### ISSUE TITLE
Server Installed Good, Agent Installed Good, I don't know how to upload / place the hashcat release

### ISSUE THREAD

**Issue by rolandbough** [curlyboi/hashtopus#61]
Server Installed Good, Agent Installed Good, I don't know how to upload / place the hashcat release so that it is distributed to the agents properly.

I followed the instructions here for my environment https://www.youtube.com/watch?v=R4VM61gzoWE

But, I don't know how to get Hashcat actually up on the server, and onto the clients.

**Comment by curlyboi** [comment]
There is a tool on my github that handles this for you.
